version: "3"
services:
  app:
    build: ./app
    environment:
      - DEBUG=app
      # ソースコードをnodemonにネットワーク越しに監視させる
      - CHOKIDAR_USEPOLLING=1
      # DB情報
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DATABASE}
    tty: true
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "80:3000"
    command: npm run dev
  db:
    image: mysql:5.7.34
    command: mysqld --character-set-server=utf8mb4
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
#      - ./db/db-data:/var/lib/mysql
#     docker volumeを使ってマウントする
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    restart: always
volumes:
  mysql_data:
